# Generated by Django 3.0.4 on 2020-03-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adquirentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adquirente', models.CharField(help_text='Informe aqui a adquirente.', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Adquirente',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do colaborador.', max_length=50)),
                ('funcao', models.CharField(help_text='Informe a função do colaborador.', max_length=10)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do estabelecimento.', max_length=50)),
                ('cnpj', models.CharField(help_text='Informe o cnpj (00.000.00/0000-00)', max_length=20)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Maquininha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sitef', 'Sitef'), ('pos', 'POS'), ('sitef_fixa', 'Sitef Fixa'), ('pos_fixa', 'POS Fixa')], max_length=10)),
                ('n_serie', models.IntegerField(help_text='Informe o Nº de serie.', unique=True)),
                ('n_logico', models.CharField(help_text='Informe o nº da etiqueta do verso.', max_length=10, unique=True)),
                ('mensalidade', models.FloatField(help_text='Informe o valor da mensalidade')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10)),
                ('data_ativacao', models.DateField(help_text='Informe a data de Ativação.')),
                ('data_inativacao', models.DateField(blank=True, help_text='Informe a data de Inativação.', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Adquirentes')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Maquininha',
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mouse', 'Mouse'), ('teclado', 'Teclado'), ('impressora', 'Impressora'), ('scanner', 'Scanner'), ('switch', 'Switch'), ('roteador', 'Roteador')], max_length=15)),
                ('marca', models.CharField(help_text='Informe a marca do equipamento.', max_length=15)),
                ('modelo', models.CharField(help_text='Informe o modelo do equipamento.', max_length=15)),
                ('service_tag', models.CharField(help_text='Informe a Service TAG do equipamento.', max_length=15, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Colaborador')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'notebook')], max_length=10)),
                ('marca', models.CharField(help_text='Informe a marca do equipamento.', max_length=15)),
                ('modelo', models.CharField(help_text='Informe o modelo do equipamento.', max_length=15)),
                ('processador', models.CharField(help_text='Informe o processador do equipamento.', max_length=15)),
                ('memoria', models.CharField(help_text='Informe a memódia do equipamento.', max_length=15)),
                ('armazenamento', models.CharField(help_text='Informe a capacidade de armazenamento do equipamento.', max_length=20)),
                ('service_tag', models.CharField(help_text='Informe a Service TAG do equipamento.', max_length=15, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Colaborador')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Equipamentos.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['tipo', 'colaborador'],
            },
        ),
    ]
